# Generated by Django 5.1.4 on 2025-01-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('data_naixement', models.DateField()),
                ('direccio', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('numero_licencia', models.CharField(max_length=20, unique=True)),
                ('historial_medico', models.TextField()),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.equip')),
            ],
        ),
    ]
